apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 8888
    targetPort: 80
  type: NodePort
  externalIPs:
  - 192.168.122.12
