apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-claim-by-label
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      type: nfs
